export function exit () {
  throw new Error(`Unrecoverable internal error`);
}
